name: Publish to NPM

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  repository_dispatch:
    types: [trigger-publish]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm install -g npm@latest
      - run: npm publish --access public
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.XCSS_NPM }}
          